version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.9.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
    logging: *default-logging
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:latest
    volumes:
      - ./config/dispatcher:/config
    links:
      - database:database
    environment:
      LOG_LAYER_START_PROCESSING: "on"
      LOG_LAYER_MATCHING: "on"
    logging: *default-logging
    labels:
      - "logging=true"
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    logging: *default-logging
    labels:
      - "logging=true"
  database:
    image: semtech/mu-authorization:0.6.0-beta.4
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  frontend:
    image: redpencil/frontend-food-forest
    environment:
      EMBER_METIS_BASE_URL: "http://food-forest.redpencil.io/"
      EMBER_YASGUI_DEFAULT_QUERY: "PREFIX voc: <http://food-forest.redpencil.io/voc/>\\nPREFIX resource: <http://food-forest.redpencil.io/resources/>\\n\\nSELECT * WHERE {\\n  ?s ?p ?o.\\n}"
      EMBER_YASGUI_EXTRA_PREFIXES: "{\\\"voc\\\":\\\"http://food-forest.redpencil.io/voc/\\\",\\\"resource\\\":\\\"http://food-forest.redpencil.io/resources/\\\"}"
    links:
      - identifier:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - virtuoso:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource-labels:
    image: lblod/resource-label-service:dev
    restart: always
    links:
      - virtuoso:database
    logging: *default-logging
    labels:
      - "logging=true"
  uri-info:
    image: redpencil/mu-uri-info-service:0.1.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
